[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "pyrage"
classifiers = [
    "Programming Language :: Rust",
    "Operating System :: POSIX :: Linux",
]
requires-python = ">=3.8"
