[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "pyrage"
classifiers = [
    "Programming Language :: Rust",
    "Operating System :: POSIX :: Linux",
]
requires-python = ">=3.8"
